name: CI/CD

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          target: app
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/djournal:${{ github.sha }}
      - name: Deploy to DO
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USER }}
          key: ${{ secrets.DIGITALOCEAN_KEY }}
          script: |
            sed -i "s/${{ secrets.DOCKER_USERNAME }}\/djournal:.*/${{ secrets.DOCKER_USERNAME }}\/djournal:${{ github.sha }}/" docker-compose.yml
            docker-compose up -d
